### ISSUE TITLE
Host via a PPA for Ubuntu users? 

### ISSUE THREAD

**Issue by mlissner** [BurntSushi/xsv#143]
I have a feeling this will get shut down pretty quickly, but I'd love it if this library (and some of your others) were available via a PPA for ubuntu. There are a few nice advantages:

 - Proper installations, rather than just a binary sitting somewhere. This could include things like man pages, if you were feeling up to it.

 - Upgrades! When you just install the binary, there's no way to know it needs an upgrade. What are the odds, for example, that somebody could make a specially crafted CSV that somehow gets exec on your machine? Low...but non-zero, I bet. What about bugs in your code that result in data loss? Possible too.

 - Simplicity of installation. I know having a binary is easy, but what happens later is that I forget where I put it and how to make it run, and then I have go sort it all out again. Yes, I can put an alias in my `.bashrc` file, but I'd rather not.

And I'm sure there are other advantages too. Any chance you'd be willing to do this? I have no idea how hard this is. What if there was a burntsushi PPA that had a bunch of your tools in it?

**Comment by BurntSushi** [comment]
You don't need to convince that this would be a lovely thing to have, but there's no way I have the bandwidth for it. I looked into doing this for ripgrep, but it looked like a _huge_ pain in the ass to me. It doesn't help that I don't use Ubuntu, so I don't really have much insight on how everything is supposed to work, so it just makes it more difficult for me to understand their documentation.

I would instead love for someone else to maintain this. Someone appears to have done something similar for ripgrep, so perhaps someone else could use that as a launching point to create a ppa for xsv: https://github.com/x4121/ripgrep-ubuntu

Finally, the Debian folks are currently hard at work trying to get ripgrep packaged into the official Debian repos. It's a lot of work because it's acting as a forcing function to simultaneously figure out how to package Rust applications. If that process gets stream lined, then it's possible xsv could go that route as well. Although, obviously that path would get updates less frequently, so a ppa might still be desirable.

**Comment by mlissner** [comment]
I'd be perfectly happy with the slow Debian updates actually, for something like this. I don't imagine it'll change too much. 

Somebody *else* offering this PPA is actually (in my mind, anyway), another reason that it needs to be done by you or by Debian folks. Like, who is this @x4121 person, anyway? Probably not somebody I'm ready to trust. 

Anyway, thanks for the reply. I kinda figured this was the response, but it's great to hear that ripgrep is coming to Debian and that it might pave the way here.

**Comment by mlissner** [comment]
I didn't mean to offend or make demands. A PPA would be great if it was trustworthy, having it in the Debian repos would probably be even better. Glad to see that's in the works.
