### ISSUE TITLE
Ability to create a Markdown table from a csv-file?

### ISSUE THREAD

**Issue by 097115** [BurntSushi/xsv#150]
As much as `--table` is great, it would be also helpful to be able to export to a **formatted** table, what do you think?

**Comment by BurntSushi** [comment]
xsv is primarily a command line tool, and I do not want it to be in the business of doing arbitrary format conversions. At least, not without a commensurate increase in maintenance commitment, which I don't see happening any time soon.

`xsv table` is useful because it permits viewing a table in a terminal. A Markdown formatted table does not achieve this directly.
