### ISSUE TITLE
Discussion: port the migration to manpage format instead?

### ISSUE THREAD

**Issue by plainas** [BurntSushi/xsv#180]
This is, to a great extent, a matter of opinion and preference. But I think it is worth having an informed discussion anyway.

I find the help system to be a little on the suboptimal side. Case point, the help system needs and has documentation about itself. I.e we need help on how to use the helping documentation.

I haven't look at the source code, but I believe this documentation is embedded in the source and output by the main application.

Granted, at this day and age, there are many command line users that don't every call ''man''. Probably most people will head up to google most of the time, but the current documentation is not available in web friendly format either. AFAIK, the documentation in the readme is distinct from that reachable through the help system.

I think a manpage would solve many of these problems. Here are some advantages I think should be taken in consideration:
* Discoverability. It is there, where it is expected to be found. Many people will just man xsv as a reflex
* Easier to skim through. Since its contents are rendered in a flat text body, users can just open it and use the find functionality of their pager, or grep it, or just read it through. In the end, it works like all other manages, not requiring to learn how to use it.
* trivially convertable to html so it can be made available on the web. In fact, github even renders manpages.

**Comment by BurntSushi** [comment]
> This is, to a great extent, a matter of opinion and preference.

You're leaving out another key aspect: development effort and portability.

The single biggest upside of the current help system is that it is simple to maintain (a single source of truth) and works even in environments that don't have a culture of using man pages (such as Windows).

If xsv were to use man pages, then I suspect end users would expect a man page for each sub-command. e.g., `man xsv select` or `man xsv sample`. This means maintaining a man page for every sub-command. Contributors who add a sub-command would also be responsible for writing said man page. Writing man pages is an arcane endeavor that requires extreme attention to detail. I know because I do provide man pages for some of my other projects.

For these reasons, I'm going to pass for now. I have some plans to overhaul xsv, but I don't know when or if I'll get to it. If I can find a simple way to provide man pages that mitigates the aforementioned downsides, then I might revisit this. But for now, this is unlikely to ever happen.
