### ISSUE TITLE
add more data to benchmarks page

### ISSUE THREAD

**Issue by jungle-boogie** [BurntSushi/xsv#19]
Hello,

Thank you for xsv and the desire to have one tool do well with a large amount of data.

I noticed you have this handy page:
https://github.com/BurntSushi/xsv/blob/master/BENCHMARKS.md

You may want to consider displaying data for less beefy systems as well, just so you can see if there's any performance differences between revisions of your code, etc.

Here's just some data running `time` on a freebsd-10.1 digital ocean droplet 1 gig of RAM droplet:
`xsv stats worldcitiespop.csv --everything  12.62s user 1.28s system 16% cpu 1:24.95 total
xsv table  0.00s user 0.00s system 0% cpu 1:24.95 total`

Certainly not as noteworthy as your results, and I understand you wouldn't really want to do heavy data science on just a gig of RAM. Do you have any input on what would contribute to the length of time it took? Or do you think this is adequate? 

Thanks!

**Comment by BurntSushi** [comment]
It's hard to say without more data. The act of passing `--everything` is essentially the user saying, "Yup, I have enough memory to load the CSV data and compute statistics that require it." (The `xsv stats --help` usage states that several statistics require storing all CSV data in memory. This is why they are optional, because they cannot be computed in an online fashion.) If your system doesn't have enough memory, then it might be swapping, which will obviously lead to a big slow down. e.g., What happens if you remove the `--everything` flag?

**Comment by jungle-boogie** [comment]
Hello,

Removing --everything time results:

`xsv stats worldcitiespop.csv  1.52s user 0.06s system 19% cpu 8.173 total
xsv table  0.01s user 0.00s system 0% cpu 8.166 total`

Far better time but interesting the CPU report is slightly more elevated.

**Comment by BurntSushi** [comment]
Well... yeah. If `--everything` causes your system to swap then it's going to make far less effective use of your system's resources.

The whole point of `xsv` is to give the user control over the resources used. This is why options like `--everything` are separated and why the docs include details like when all of the CSV data needs to be read into memory. This is especially important in your case because you're running it on a system with constrained resources. Therefore, you must be cognizant of what resources you want to let `xsv` use.

A helpful tool is `time -v` because it can report the maximum memory usage of the process, including user/system time. On a 3.4 GHz Intel i5 with 4 threads, here are some results.

Running `xsv stats --everything`:

```
[andrew@Serval tmp] /usr/bin/time -v xsv stats worldcitiespop.csv --everything > /dev/null
        Command being timed: "xsv stats worldcitiespop.csv --everything"
        User time (seconds): 31.49
        System time (seconds): 0.32
        Percent of CPU this job got: 218%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:14.58
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1425376
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 69738
        Voluntary context switches: 2084
        Involuntary context switches: 3759
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Notice the memory usage required: over 1.4GB! Now let's try without `--everything`:

```
[andrew@Serval tmp] /usr/bin/time -v xsv stats worldcitiespop.csv > /dev/null
        Command being timed: "xsv stats worldcitiespop.csv"
        User time (seconds): 3.67
        System time (seconds): 0.02
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:03.70
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 15404
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 162
        Voluntary context switches: 36
        Involuntary context switches: 45
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Memory usage has shrunk to 15MB (which should be constant, probably as a result of the IO buffer). Moreover, the time required has decreased several fold. This is because the stats computed in `--everything` (like cardinality and median) require a lot more resources.

If you create an index with `xsv index worldcitiespop.csv`, then it goes even faster if you have multiple cores:

```
[andrew@Serval tmp] /usr/bin/time -v xsv stats worldcitiespop.csv > /dev/null
        Command being timed: "xsv stats worldcitiespop.csv"
        User time (seconds): 3.83
        System time (seconds): 0.01
        Percent of CPU this job got: 370%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.03
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 25112
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 237
        Voluntary context switches: 82
        Involuntary context switches: 1005
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

My recommendation to you is to carefully read `xsv`'s documentation and be more cognizant of the available system resources and how `xsv` uses them. If you find an inconsistency there, then that probably means the docs could be improved.

**Comment by jungle-boogie** [comment]
Hello,

> My recommendation to you is to carefully read xsv's documentation and be more cognizant of the available system resources and how xsv uses them. 

great advice/idea.

Thank you for creating xsv and tolerating my many opened issues. 

Best,
sean

**Comment by jungle-boogie** [comment]
Hello,

turns out `time -l` within freebsd is somewhat the verbose version on linux.

       70.77 real        57.90 user         6.08 sys
    726660  maximum resident set size
      2086  average shared memory size
        47  average unshared data size
       127  average unshared stack size
     1155193  page reclaims
     26311  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
     26402  voluntary context switches
      6489  involuntary context switches
