### ISSUE TITLE
[New Feature] Filter records based on field based query expressions

### ISSUE THREAD

**Issue by JavaScriptDude** [BurntSushi/xsv#208]
I have a business need to filter records in large flat files based on wildcard or regular expression based against on data within specific fields rather than across entire records.

For instance, for a file with a flat file containing the following fields: fname, path, size, extension, flag1, I would like to write a query like --query "path = '(*foo*' AND name = '*test*' OR path = '*bar*' AND name = '*test2*') AND flag1 = 'x'". This would filter the data such that only the records matching the above expression would be in the results. Also, adding a --subset flag would reverse the output by returning the records excluded by the query. 

Would you consider taking a pull request to add a query feature to xsv? I know it could be a rather large addition to this code base.

**Comment by BurntSushi** [comment]
xsv is never going to have its own domain specific query language. The goal of xsv is not to re-invent SQL. If you want SQL-level expression, then I'd recommend loading the data into SQLite.

With that said, you can pretty much already achieve what you want using `xsv` today and shell pipelines. In particular, you seem to be under the impression that you can only search across an entire record. But `xsv search` has a `-s/--select` flag that permits restricting your search to specific fields:

```
$ xsv search -s flag1 '^x$' input.csv \
    | xsv search -s path '^(foo|bar)$'
    | xsv search -s name '^(test|test2)$'
```

I'm not sure if I captured your query semantics accurate because your parentheses look off, but you get the idea.

**Comment by JavaScriptDude** [comment]
Sorry I misunderstood that search feature on my initial read through.  Looks intuitive and will cover 99% of the usecases I have for flat files. The SQLite solution would be an easy stop gap for the outliers.

Thanks for the excellent tool and great code.
