### ISSUE TITLE
Please add Contributing.md

### ISSUE THREAD

**Issue by Moizsohail** [BurntSushi/xsv#299]
I am looking to contribute to a  rust project. And this open source project caught my eye on [Code Triage](https://www.codetriage.com/burntsushi/xsv). I was hoping if anyone can add a small Contributing.md to get started on this project.

**Comment by BurntSushi** [comment]
This project isn't terribly active at the moment. So that's the primary problem. Not the lack of onboarding docs.

Before contributing to a project, consider checking things like the last commit date and the last time a PR was merged.

I don't know what codetriage is, but it looks like auto generated garbage that has misled you.

**Comment by Moizsohail** [comment]
Thank you. I will.
