### ISSUE TITLE
GLIBC_2.18 not found (possible to link statically instead of dynamically?)

### ISSUE THREAD

**Issue by nekromoff** [BurntSushi/xsv#3]
:~/xsv-0.8.14-x86_64-unknown-linux-gnu$ ./xsv
./xsv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by ./xsv)

:~$ ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.10) 2.15

**Comment by BurntSushi** [comment]
I think you mean: can I link statically instead of dynamically?

Alternatively, I could release binaries compiled with an older `glibc`. I suspect I'll go this route, because I'm not sure how to produce completely static binaries with `rustc`. But it unfortunately might be a bit before I have the infrastructure in place to do it.

**Comment by nekromoff** [comment]
yeah, i meant static linking.
that's fine, i don't need it at the moment, but in the future for sure.
keep good work.

**Comment by ostrokach** [comment]
If you are using conda, XSV is available from the bioconda channel: https://anaconda.org/bioconda/xsv.

It is compiled on a CentOS 5.11 docker image with glibc 2.5, so it should be compatible with all non-archaic Linux releases.

**Comment by BurntSushi** [comment]
The [releases](https://github.com/BurntSushi/xsv/releases) page now includes completely static binaries for Linux using `musl`.
