### ISSUE TITLE
Feature request: Add sugar for `| tail -n+2`

### ISSUE THREAD

**Issue by Armavica** [BurntSushi/xsv#30]
I feel almost ashamed to ask for a feature that has such an easy workaround, but sometimes, I need to manipulate a CSV file, select rows and columns based on their headers, and output a table *without headers*.  The `--no-headers` option is of no help because I rely on the headers of the input file.  The workaround on Unix is `| tail -n+2`, but I believe that an option in `xsv` to implement this behaviour could make sense as well.

Is it worth considering adding this feature?

**Comment by BurntSushi** [comment]
What about `xsv select col1,col2 data.csv | xsv slice -ns 1 | xsv table`?

**Comment by Armavica** [comment]
That is even longer than `| tail -n+2` ;)  I was more thinking of a flag for this in the "Common options" section but I would completely understand if you found that unnecessary.

**Comment by BurntSushi** [comment]
FWIW, `tail -n+2` isn't correct, since header names can contain new lines. In general, one can't use standard unix utilities with CSV data because of that.

I think I'd rather not increase the number of common options. Too many options makes tools harder to use IMO. I think I'd rather encourage the user to define their own short-cuts. For example, to get your table output without headers:

```
alias xsv-noh-table="xsv slice --no-headers --start 1 | xsv table"
xsv select col1,col2 data.csv | xsv-noh-table
```

Or something like that.

**Comment by Armavica** [comment]
Alright, thank you very much for your answers.
