### ISSUE TITLE
Feature request: export to an SQL database

### ISSUE THREAD

**Issue by DemiMarie** [BurntSushi/xsv#40]
Reading the README brought to mind the thought "What if xsv could export to an SQL database?".

SQLite is the most logical one, since it's small.

**Comment by BurntSushi** [comment]
I'm personally not that interested in maintaining a feature like this for a couple reasons:

1. There are other tools that can do this for you.
2. `xsv` is a tool to process CSV very quickly. If you only want to process the data once so that you can put it into a database, then that reduces the value proposition of `xsv` significantly.
3. I'm personally not that interested in specifically maintaining a feature like this. It feels like a lot of work.
