### ISSUE TITLE
Q: Does xsv have an equivalent operation to csvkit's csvclean ?

### ISSUE THREAD

**Issue by kmatt** [BurntSushi/xsv#79]
I need a fast filter to parse csv file lines and drop those that are unparsable, as with https://csvkit.readthedocs.io/en/1.0.2/scripts/csvclean.html. csvclean works in a shell pipe (PR 781) but is limited in speed.

Does xsv have a similar method?

**Comment by BurntSushi** [comment]
> drop those that are unparsable

In order to have such a command, you first need to define what it means to be "unparseable." Can you provide an example? Note that xsv's underlying CSV library specifically rejects the idea that any CSV data is unparseable. Instead, it always attempts to find a parse. This is similar to how Python's CSV parser works.

Also, this is `xsv`, not `csvtk`. :P

**Comment by kmatt** [comment]
The case in question is when there are either unbalanced quotes, or linebreaks within columns that cause regular parsers to fail, such as when loading csv data into PostgreSQL via 'cat ... | psql -c "copy ..."

I'm using csvclean to simply throw those lines out, and allow the DB to ingest the "normally formatted" lines.

**Comment by BurntSushi** [comment]
@emk Do you have any experience with this sort of problem?

My intuition here is that this would be a hard command to add. The first major problem is that the csv library that xsv uses doesn't have the ability detect invalid CSV. So that functionality would need to be added first. It would be a fun exercise, but given the complexity of the csv parser, it would be non-trivial.

I'll leave this open for now, but honestly, I wouldn't expect this any time soon. If you really wanted this sooner, then I'd recommend hand rolling a CSV parser yourself in Rust. You could start with the NFA that never yields an error: https://github.com/BurntSushi/rust-csv/blob/19cc86561f7c51622bd9bc3a1cda17a7052e3c54/csv-core/src/reader.rs#L927-L1018 --- But this is likely only viable if you're interested in learning Rust. :-)

**Comment by BurntSushi** [comment]
Come to think of it, I wonder if this would be easier to add to the csv library than I thought... I added an issue for it: https://github.com/BurntSushi/rust-csv/issues/77

**Comment by kmatt** [comment]
An Awk example to pass only rows with the same number of fields as the header:

    gawk -vFPAT='[^,]*|\"[^\"]*\"' 'NR == 1 { print NF; fc = NF }; NF == fc { print }' test.csv

**Comment by BurntSushi** [comment]
@kmatt Well, that could actually be done today I think. The CSV parser does support toggling whether rows of varying lengths are allowed. (But the xsv sub-command itself would still need to be written. I just mean that the underlying library supports it.)

**Comment by emk** [comment]
@kmatt The [scrubcsv](https://github.com/faradayio/scrubcsv) tool is built around some slightly abusive misuse of the `csv` library, and it can deal with certain kinds of mangled CSV files. It tries to patch up malformed quotes (not always 100% correctly), and throws out rows that have the wrong number of columns after repair. If more than 5% of the rows are bad, it rejects the file outright (though we could make that tunable, I suppose). It cleans at roughly 75 MB/s on my laptop.

We routinely run this on 100s of GBs of pretty ugly "CSV" data, spread out across a [Pachyderm](https://www.pachyderm.io/) / Kubernetes cluster.

(We also have [catcsv](https://github.com/faradayio/catcsv), which is like `xsv cat rows`, except that you can pass it entire directory tress of `*.csv` or `*.csv.sz` files. We make very heavy use of @BurntSushi's `szip` at Faraday for compression of intermediate data during big cluster jobs. Basically we're huge @BurntSushi fans. :-) Which is how I got permission to contribute `xsv partition`!)
